### ISSUE TITLE
Error in side-posted resource doesn't rollback transaction

### ISSUE THREAD

**Issue by mozcomp** [graphiti-api/graphiti_old_archived#38]
Just encountered a minor issue when doing a side-posted has_many save.
If there is an error saving one of the children, it should rollback the entire transaction.
It does if the error occurs on the last child, but if a subsequent child is successfully saved, it doesn't.
Moving the child that should error to be the last, I get the expected behaviour - code: 422, 'unprocessable_entity'
Let me know if you need any further detail

**Comment by richmolj** [comment]
Very surprising - will move to my short-term list. Thanks for the heads up!

**Comment by richmolj** [comment]
Fixed in `1.0.beta.11` 👍
