### ISSUE TITLE
Is this JSON:API?

### ISSUE THREAD

**Issue by ahx** [graphiti-api/graphiti_old_archived#40]
I know that you are probably in the early stages of the project, but I am a little bit confused about what the plans for this project are – I am looking for libraries / frameworks that help us implementing a [JSON:API](http://jsonapi.org/) compliant server – Is graphiti for us or are you planning to derive from the JSON:API spec?

I guess the claim ["A stylish alternative to GraphQL."](https://graphiti-api.github.io/graphiti/) got me is a little confused.

**Comment by richmolj** [comment]
Hi @ahx - the JSONAPI specification is our first-class citizen (this project used to be called [JSONAPI Suite](https://jsonapi-suite.github.io/jsonapi_suite). But we also added to the spec (backwards-compatible) and support more content types and renderings. In other words the JSONAPI specification is a lower-level here; Graphiti uses JSONAPI like REST uses HTTP.
