### ISSUE TITLE
Where are @url_helpers

### ISSUE THREAD

**Issue by hector** [graphiti-api/graphiti_old_archived#44]
One can customize the display of resource attributes.
For example, the instance of the data model is accesed with `@object`:
https://graphiti-api.github.io/graphiti/guides/concepts/resources#customizing-display

In jsonapi-suite I was also using @url_helpers to generate urls but in graphiti is not available anymore. Has the name changed?

**Comment by richmolj** [comment]
Yeah, this was removed as part of Rails decoupling. I'd change this to:

```ruby
# application_resource.rb
def url_helpers
  Rails.application.routes.url_helpers
end
```

```ruby
class PostResource < ApplicationResource
  attribute :link, :string do
    url_helpers.posts_path
  end
end
```

**Comment by hector** [comment]
Thanks! Now I feel stupid I haven't thought about that :)
