### ISSUE TITLE
Is there a way to avoid pagination on ActiveRecord resources?

### ISSUE THREAD

**Issue by hector** [graphiti-api/graphiti_old_archived#45]
Is there a way to avoid pagination on ActiveRecord resources?

For now I have rolled my own solution, but maybe there is a better approach or a built-in.

```ruby
class ApplicationResource < Graphiti::Resource
  # Use the ActiveRecord Adapter for all subclasses.
  # Subclasses can still override this default.
  self.abstract_class = true
  self.adapter = Graphiti::Adapters::ActiveRecord
  self.base_url = Rails.application.routes.default_url_options[:host]
  self.endpoint_namespace = '/api'

  # Overwrite default pagination behaviour to allow no pagination using negative pages
  paginate do |scope, current_page, per_page|
    if current_page < 0
      scope
    else
      scope.page(current_page).per(per_page)
    end
  end

end
```

**Comment by richmolj** [comment]
This seems correct to me. The other thing you could do is subclass the adapter and override the paginate method.

That said, I'm not sure it ever makes sense to paginate on negative numbers, so maybe this should get into master.

**Comment by wadetandy** [comment]
> That said, I'm not sure it ever makes sense to paginate on negative numbers, so maybe this should get into master.

I think this would be a good addition, though it should be able to be disabled globally at the `ApplicationResource` level for APIs that want to force pagination.

**Comment by wadetandy** [comment]
(and should probably be disabled by default to prevent accidental DOS)

**Comment by hector** [comment]
I agree, this is something I am only going to enable for a few resources.

**Comment by richmolj** [comment]
I'd be down for a PR, but I think the current solution isn't too bad. If we want to resume this, let's do it at https://github.com/graphiti-api/graphiti
