### ISSUE TITLE
Rails < 5.2 compatibility and generators

### ISSUE THREAD

**Issue by thec0keman** [graphiti-api/graphiti_old_archived#71]
The resource generator assumes that `Rails::Generators::NamedBase` defines a `plural_route_name` attribute, which was only introduced in Rails 5.2.

I'm guessing a fallback to `plural_table_name` is sufficient

**Comment by richmolj** [comment]
Ah, good to know, thanks for the heads up. Care to submit a PR?

**Comment by richmolj** [comment]
Moving discussion to PR
